backbone:
- - -1
  - 1
  - Conv
  - - 64
    - 3
    - 2
- - -1
  - 1
  - Conv
  - - 128
    - 3
    - 2
- - -1
  - 3
  - C2f
  - - 128
    - true
- - -1
  - 1
  - Conv
  - - 256
    - 3
    - 2
- - -1
  - 6
  - DCN_SCC_C2f
  - - 256
    - true
- - -1
  - 1
  - Conv
  - - 512
    - 3
    - 2
- - -1
  - 6
  - DCN_SCC_C2f
  - - 512
    - true
- - -1
  - 1
  - Conv
  - - 1024
    - 3
    - 2
- - -1
  - 3
  - C2f
  - - 1024
    - true
head:
- - -1
  - 1
  - Conv
  - - 512
    - 1
    - 1
- - - -1
    - 6
  - 1
  - Concat
  - - 1
- - -1
  - 3
  - C2f
  - - 512
- - -1
  - 1
  - Conv
  - - 256
    - 1
    - 1
- - - -1
    - 4
  - 1
  - Concat
  - - 1
- - -1
  - 3
  - C2f
  - - 256
- - -1
  - 1
  - Conv
  - - 256
    - 3
    - 2
- - - -1
    - 12
  - 1
  - Concat
  - - 1
- - -1
  - 3
  - C2f
  - - 256
- - -1
  - 1
  - Conv
  - - 512
    - 3
    - 2
- - - -1
    - 9
  - 1
  - Concat
  - - 1
- - -1
  - 3
  - C2f
  - - 512
- - - 15
    - 18
    - 21
  - 1
  - Detect
  - - nc
nc: 80
scales:
  n:
  - 0.33
  - 0.25
  - 1024
